name = "Word2Vec"
uuid = "646652a7-79fc-4b5e-901d-cd688489453a"
authors = ["Maximilian Hans hans.maximilian@icloud.com"]
version = "1.0.0-DEV"

[deps]
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"

[compat]
DelimitedFiles = "1.9.1"
julia = "1.11"
